# 1. reshape()

In [ ]:
# Syntax -> array_name.reshape(dimensions)
# It used to change the shape of the array

In [4]:
import numpy as np

In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr = arr.reshape(3,2,2)
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

# 2.nditer()

In [19]:
# In python if there is multidimensional array or list then we have to use multiple for loops but by using nditer() we can direct access the each element of  Array list/ sublists

In [22]:
# In python

arr = [[[1,2,3,4],[5,6,7,8],[2,6,3,7]]]
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
2
6
3
7

In [23]:
# By Using Numpy

arr = np.array([[[1,2,3,4],[5,6,7,8],[2,6,3,7]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
2
6
3
7

# 3. np.ndenumerate()

In [ ]:
# It return the values with indices

In [2]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
for i, val in np.ndenumerate(arr):
    print(i,">>",val)

(0, 0) >> 1
(0, 1) >> 2
(0, 2) >> 3
(1, 0) >> 4
(1, 1) >> 5
(1, 2) >> 6
(2, 0) >> 7
(2, 1) >> 8
(2, 2) >> 9

In [10]:
arr1=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
])
print("shape:",arr1.shape)
for i, val in np.ndenumerate(arr1):
    print(i, val)

shape: (1, 3, 3)
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9

# 4. zeros()

In [ ]:
# np.zeros(shape,dtype=float)

# Returns an array of zero
# To create reference column
# Default datatype --> float

In [7]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros(5,dtype=int)
arr

array([0, 0, 0, 0, 0])

In [14]:
# No need to write "dtype" keyword to pass datatype we can direct pass datatype

arr = np.zeros(10, int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# passing shape of array

arr = np.zeros([5,2] , int)
print(arr.ndim)
arr

2

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [25]:
arr = np.zeros([5,2,2],int)
print(arr.ndim)
arr

3

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

# 5. ones()

In [26]:
# It creates array of ones

In [28]:
arr = np.ones(5, int)
arr

array([1, 1, 1, 1, 1])

In [34]:
# passing shape

arr = np.ones([5,3,2], int)
print("shape:",arr.shape)
print("dimension:", arr.ndim)
arr

shape: (5, 3, 2)
dimension: 3

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

# 6. arange()

In [ ]:
# arr = np.arange(start, stop, step)
# It creates a aray of the range passed to it
# It is similar to range() function in python

In [3]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [35]:
arr = np.arange(5,10)
arr

array([5, 6, 7, 8, 9])

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr = np.arange(3,6)
arr

array([3, 4, 5])

In [38]:
arr1 = np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

In [40]:
arr1 = np.arange(0,20,-1) # For negative indexing start value mist be greater than stop value otherwisse array will be empty
arr1

array([], dtype=int64)

In [42]:
arr1 = np.arange(10,0,-1) # So we can write array in reverse order by using Negative indexing
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [43]:
arr1 = np.arange(20,0,-2)
arr1

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [44]:
arr1 = np.arange(-5, 6)
arr1

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [4]:
arr1 = np.arange(6,-5)
arr1 # print empty array

array([], dtype=int64)

In [47]:
arr1 = np.arange(6,-5,-1)
arr1

array([ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4])

# 7. linspace()

In [48]:
# np.linspace(start, end, num = 50)
# start is the starting value and end is the ending value means the array will be generated between this two values.
# num is the count of values that will be genarated by default it os 50.
# It returns  evenly spaced values.
# By default num is 50 means it returns 50 values by default 
# Evenly spaced means the difference of two vaalues is same.

In [49]:
arr = np.linspace(1,10)
arr
# generate the 50 values in between 1 to 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [51]:
arr = np.linspace(20, 25,num = 10)
arr
# generate 10 values in bteween 20 to 25

array([20.        , 20.55555556, 21.11111111, 21.66666667, 22.22222222,
       22.77777778, 23.33333333, 23.88888889, 24.44444444, 25.        ])

In [52]:
# To print the difference between each two values of use "retstep=True"

In [54]:
arr = np.linspace(10,50, num = 20, retstep = True)
print(arr)

(array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
       20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
       31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
       41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ]), np.float64(2.1052631578947367))

In [55]:
arr = np.linspace(10,50, num = 20, retstep = True)
arr

(array([10.        , 12.10526316, 14.21052632, 16.31578947, 18.42105263,
        20.52631579, 22.63157895, 24.73684211, 26.84210526, 28.94736842,
        31.05263158, 33.15789474, 35.26315789, 37.36842105, 39.47368421,
        41.57894737, 43.68421053, 45.78947368, 47.89473684, 50.        ]),
 np.float64(2.1052631578947367))

In [56]:
arr = np.linspace(10,50, num = 20, retstep = False)
print(arr)

[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]

In [59]:
# We can difference using "(end-start)/num)"

arr = np.linspace(5,100, num=100)
print (arr)
print("Difference is:",(100-5)/100)

[  5.           5.95959596   6.91919192   7.87878788   8.83838384
   9.7979798   10.75757576  11.71717172  12.67676768  13.63636364
  14.5959596   15.55555556  16.51515152  17.47474747  18.43434343
  19.39393939  20.35353535  21.31313131  22.27272727  23.23232323
  24.19191919  25.15151515  26.11111111  27.07070707  28.03030303
  28.98989899  29.94949495  30.90909091  31.86868687  32.82828283
  33.78787879  34.74747475  35.70707071  36.66666667  37.62626263
  38.58585859  39.54545455  40.50505051  41.46464646  42.42424242
  43.38383838  44.34343434  45.3030303   46.26262626  47.22222222
  48.18181818  49.14141414  50.1010101   51.06060606  52.02020202
  52.97979798  53.93939394  54.8989899   55.85858586  56.81818182
  57.77777778  58.73737374  59.6969697   60.65656566  61.61616162
  62.57575758  63.53535354  64.49494949  65.45454545  66.41414141
  67.37373737  68.33333333  69.29292929  70.25252525  71.21212121
  72.17171717  73.13131313  74.09090909  75.05050505  76.01010101
  76.96969697  77.92929293  78.88888889  79.84848485  80.80808081
  81.76767677  82.72727273  83.68686869  84.64646465  85.60606061
  86.56565657  87.52525253  88.48484848  89.44444444  90.4040404
  91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]
Difference is: 0.95

In [61]:
import pandas as pd

In [63]:
df = pd.DataFrame(arr)
df

             0
0     5.000000
1     5.959596
2     6.919192
3     7.878788
4     8.838384
..         ...
95   96.161616
96   97.121212
97   98.080808
98   99.040404
99  100.000000

[100 rows x 1 columns]

In [65]:
 df['1'] = np.linspace(40, 45, num=100)
df

             0          1
0     5.000000  40.000000
1     5.959596  40.050505
2     6.919192  40.101010
3     7.878788  40.151515
4     8.838384  40.202020
..         ...        ...
95   96.161616  44.797980
96   97.121212  44.848485
97   98.080808  44.898990
98   99.040404  44.949495
99  100.000000  45.000000

[100 rows x 2 columns]

# 8. eye()

In [ ]:
# np.eye(value) - It makes an array of size given as value 
# np.eye(row,column, dtype = data type)
# np.eye(row,column, index)

# It makes only 2-D array 
# It makes an array or the matix of given size with 1 at diagonal.
# We can change the position of diagonal 1's by passing third parameter which is index from 1 start appearing diagonally

In [67]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
arr = np.eye(4,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [70]:
arr = np.eye(5,5, dtype=float)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
arr = np.eye(5,5, dtype= int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [74]:
arr = np.eye(4,5,0, dtype=int) # Diagonal 1 are from index 0
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

In [73]:
arr = np.eye(4,5,1) # Diagonal 1 are from index 1
arr

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [75]:
arr = np.eye(4,5,-1, dtype=int) # Diagonal 1 are from index -1
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [76]:
arr = np.eye(5,5,2, dtype=int) # Diagonal 1 are from index 2
arr

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
arr = np.eye(5,5,4, dtype=int) # Diagonal 1 are from index 4
arr

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [78]:
arr = np.eye(5,5,-3, dtype=int) # Diagonal 1 are from index -3
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

# 9. identity()

In [ ]:
# np.identity(number of rows and columns , dtype)
# It includes same rows amd same columns
# 1's are diagonally present

In [79]:
arr = np.identity(5,dtype=int)
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [80]:
arr = np.identity(10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [81]:
# Making the dataframe of given functions

In [85]:
dict = {'zeros':np.zeros(10),
        'ones':np.ones(10),
        'arange':np.arange(10, 20),
       'linspace':np.linspace(100,200, num=10)
       }
dict

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'arange': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 'linspace': array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])}

In [86]:
df = pd.DataFrame(dict)
df

   zeros  ones  arange  linspace
0    0.0   1.0      10      10.0
1    0.0   1.0      11      20.0
2    0.0   1.0      12      30.0
3    0.0   1.0      13      40.0
4    0.0   1.0      14      50.0
5    0.0   1.0      15      60.0
6    0.0   1.0      16      70.0
7    0.0   1.0      17      80.0
8    0.0   1.0      18      90.0
9    0.0   1.0      19     100.0

In [ ]:
# NaN >> Not a Number
# NaT >> Not a Time

In [93]:
df['list1'] = [9,8,7,6,np.nan,5,4,3,2,1]
df

   zeros  ones  arange  linspace  list1
0    0.0   1.0      10      10.0    9.0
1    0.0   1.0      11      20.0    8.0
2    0.0   1.0      12      30.0    7.0
3    0.0   1.0      13      40.0    6.0
4    0.0   1.0      14      50.0    NaN
5    0.0   1.0      15      60.0    5.0
6    0.0   1.0      16      70.0    4.0
7    0.0   1.0      17      80.0    3.0
8    0.0   1.0      18      90.0    2.0
9    0.0   1.0      19     100.0    1.0

# 10. random

In [ ]:
Used to genarate random number

1. rand() - Generates the random value between 0 to 1
2. randint() - Generates the random integer value
3. randn() - Generates the normally distributed value
4. randf() - Generates the random value

## 10.1. random.rand()

In [94]:
# It returns values between zero and one.

In [95]:
arr = np.random.rand(5)
arr

array([0.45276098, 0.06588336, 0.63287738, 0.04021294, 0.28670677])

In [96]:
arr = np.random.rand(50)
arr

array([0.94008452, 0.04376703, 0.53772612, 0.15645478, 0.69991193,
       0.87263933, 0.19164917, 0.02118607, 0.25971591, 0.44424334,
       0.68670184, 0.44752896, 0.19748771, 0.63645779, 0.02003305,
       0.1010943 , 0.30190969, 0.40182698, 0.18311516, 0.26257571,
       0.34920706, 0.79656412, 0.84865515, 0.85385117, 0.97270702,
       0.25602368, 0.2276074 , 0.27977338, 0.48400788, 0.02060328,
       0.06888441, 0.81779087, 0.8212676 , 0.64661163, 0.5048105 ,
       0.15704833, 0.17781398, 0.52914811, 0.98795795, 0.72238562,
       0.79482321, 0.44163292, 0.56724957, 0.78259132, 0.57407416,
       0.53355616, 0.91930018, 0.09993661, 0.75173624, 0.57590167])

In [98]:
arr = np.random.rand(5,5)
arr

array([[0.43318906, 0.66202275, 0.66041437, 0.29340739, 0.73186759],
       [0.42515137, 0.97842167, 0.96781743, 0.66225674, 0.85668687],
       [0.80626936, 0.67070551, 0.4198286 , 0.57148275, 0.9692948 ],
       [0.15172586, 0.93019815, 0.93667869, 0.86185604, 0.62047674],
       [0.33930859, 0.2727922 , 0.23764648, 0.87356114, 0.96136693]])

In [12]:
arr = np.random.rand(5,3,3) # 3-D array
arr

array([[[0.68829521, 0.29018684, 0.79219245],
        [0.67369103, 0.20306602, 0.60121623],
        [0.3697906 , 0.71885754, 0.25377345]],

       [[0.45488327, 0.18162016, 0.83623042],
        [0.01473938, 0.12960083, 0.23746003],
        [0.14820764, 0.10423235, 0.06985868]],

       [[0.79528646, 0.78181151, 0.86964253],
        [0.13313022, 0.8110175 , 0.2968806 ],
        [0.34112508, 0.77026261, 0.80802633]],

       [[0.04559805, 0.58590471, 0.60677085],
        [0.76464642, 0.13774108, 0.92696069],
        [0.6432759 , 0.89083998, 0.05129522]],

       [[0.83298883, 0.05492675, 0.66826659],
        [0.61058768, 0.60172827, 0.51388251],
        [0.65843192, 0.77624897, 0.77064385]]])

## 10.2. random.randint()

In [101]:
# np.random.randint(start, stop, size=  )

In [110]:
arr = np.random.randint(10,20)
arr

11

In [109]:
arr = np.random.randint(10,20, size = 20)
arr

array([10, 15, 13, 18, 16, 18, 19, 11, 13, 12, 18, 11, 14, 17, 18, 12, 17,
       15, 18, 15], dtype=int32)

In [113]:
# To generate 2-D array take size = (rows, columns)

arr = np.random.randint(10,20,size = (5,6))
arr

array([[12, 14, 14, 17, 18, 14],
       [13, 16, 10, 15, 10, 12],
       [14, 10, 12, 11, 16, 11],
       [13, 16, 11, 13, 12, 19],
       [15, 10, 10, 13, 15, 13]], dtype=int32)

In [115]:
df = pd.DataFrame(arr)
df

    0   1   2   3   4   5
0  12  14  14  17  18  14
1  13  16  10  15  10  12
2  14  10  12  11  16  11
3  13  16  11  13  12  19
4  15  10  10  13  15  13

## 10.3. random.randn()

In [ ]:
# returns normally distributed value
# Normally distributed values are used to make GRAPH from values(includes mean, standard deviation)
# mean is maximum value and std deviation are positive and negative values less than mean on graph(Bell Curve)

In [2]:
import numpy as np

In [3]:
arr = np.random.randn(10)
arr

array([-0.30270452, -0.16294321,  1.22599349, -1.49664222, -0.06066083,
       -1.00248971, -1.03398923, -0.51776959,  1.74154938,  1.04754   ])

In [18]:
# for 2-D

arr = np.random.randn(4,3)
arr

array([[ 0.40742974, -0.84029354,  0.3840464 ],
       [ 0.89451666,  0.59393545,  0.35984234],
       [-0.00541672, -0.93573268,  0.41528265],
       [-0.5172927 ,  1.88156178,  0.8618075 ]])

## 10.4. random.ranf()

In [ ]:
# It is same as random.rand() but only returns the float values
# It returns the float values between 0.0 to 1.0
# Wew can generate the 1-D array only to genarate the 2-D array we have to pass the parameters inside the tuple

In [6]:
arr = np.random.ranf(5)
arr

array([0.06032295, 0.47310399, 0.51288104, 0.62326279, 0.28795831])

In [19]:
arr = np.random.randf(5,4)
arr

AttributeError: module 'numpy.random' has no attribute 'randf'

In [8]:
arr = np.random.ranf((5,4))
arr

array([[0.29520872, 0.72822628, 0.84752083, 0.41422062],
       [0.05688949, 0.41497722, 0.67543729, 0.75400786],
       [0.93304866, 0.33338893, 0.12477288, 0.55276298],
       [0.60481972, 0.00145445, 0.40708401, 0.32899492],
       [0.28272644, 0.8739283 , 0.88105737, 0.17795572]])

In [13]:
import pandas as pd

In [15]:
dict3 = {'zeros':np.zeros(10),
        'ones':np.ones(10),
        'arange':np.arange(10, 20),
        'linspace':np.linspace(100,200, num=10),
        'random_int':np.random.randint(10,50, size=10),
        'randn':np.random.randn(10),
        'ranf':np.random.ranf(10)
       }
dict3

{'zeros': array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 'ones': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 'arange': array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),
 'linspace': array([100.        , 111.11111111, 122.22222222, 133.33333333,
        144.44444444, 155.55555556, 166.66666667, 177.77777778,
        188.88888889, 200.        ]),
 'random_int': array([48, 24, 28, 18, 48, 42, 15, 44, 17, 18], dtype=int32),
 'randn': array([ 0.81012361,  0.08949622,  1.31140544, -1.69194159, -0.09128187,
        -0.99968263,  0.20822322,  0.20860291,  0.6776356 , -0.10152288]),
 'ranf': array([0.44592132, 0.7373846 , 0.62609421, 0.49086097, 0.91160632,
        0.11053651, 0.43633037, 0.89703694, 0.77395543, 0.84751475])}

In [16]:
df3 = pd.DataFrame(dict3)
df3

   zeros  ones  arange    linspace  random_int     randn      ranf
0    0.0   1.0      10  100.000000          48  0.810124  0.445921
1    0.0   1.0      11  111.111111          24  0.089496  0.737385
2    0.0   1.0      12  122.222222          28  1.311405  0.626094
3    0.0   1.0      13  133.333333          18 -1.691942  0.490861
4    0.0   1.0      14  144.444444          48 -0.091282  0.911606
5    0.0   1.0      15  155.555556          42 -0.999683  0.110537
6    0.0   1.0      16  166.666667          15  0.208223  0.436330
7    0.0   1.0      17  177.777778          44  0.208603  0.897037
8    0.0   1.0      18  188.888889          17  0.677636  0.773955
9    0.0   1.0      19  200.000000          18 -0.101523  0.847515