# Pandas

In [2]:
import numpy as np
import pandas as pd

## Read CSV/EXCEL File

### pd.readd_csv()

In [34]:
df = pd.read_csv('customers-1000.csv')
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

### pd.read_excel()

In [32]:
# to read the EXCEL file we use ->> pd.read_excel()

file = r'C:\Users\admin\Downloads\file_example_XLSX_10.xlsx'  # we can read file from local storage by giving the path of the file 
df = pd.read_excel(file)
df

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

# Pandas Basic Functions

In [65]:
user_df = pd.read_excel(r'C:\Users\admin\Downloads\file_example_XLSX_10.xlsx')
user_df

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

### shape

In [45]:
shape = user_df.shape # It gives the shape i.e number of rows and columns.
print('Shape of file is : ', shape)

rows_count = user_df.shape[0]  # No.of rows

column_count = user_df.shape[1] # No. of columns

print('Number of rows are : ', rows_count)
print('Number of columns are : ', column_count)

Shape of file is :  (9, 8)
Number of rows are :  9
Number of columns are :  8

### columns

In [51]:
user_df.columns    # It gives all the columns inside dataframe

Index([0, 'First Name', 'Last Name', 'Gender', 'Country', 'Age', 'Date', 'Id'], dtype='object')

### index

In [52]:
 user_df.index # It returns the index range i.e start, stop and step

RangeIndex(start=0, stop=9, step=1)

### axes

In [54]:
user_df.axes # It returns both i.e index range and column names inside dataframe

[RangeIndex(start=0, stop=9, step=1),
 Index([0, 'First Name', 'Last Name', 'Gender', 'Country', 'Age', 'Date', 'Id'], dtype='object')]

### .info()

In [59]:
user_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   0           9 non-null      int64
 1   First Name  9 non-null      object
 2   Last Name   9 non-null      object
 3   Gender      9 non-null      object
 4   Country     9 non-null      object
 5   Age         9 non-null      int64
 6   Date        9 non-null      object
 7   Id          9 non-null      int64
dtypes: int64(3), object(5)
memory usage: 708.0+ bytes

### .describe()

In [63]:
print(user_df)

user_df.describe()  # It returns the stats (mean, std, min, max, and 25%, 50%, 75%) of all Numerical columns

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

              0        Age           Id
count  9.000000   9.000000     9.000000
mean   5.000000  35.888889  2989.333333
std    2.738613  13.147666  1511.344517
min    1.000000  24.000000  1562.000000
25%    3.000000  25.000000  2456.000000
50%    5.000000  32.000000  2554.000000
75%    7.000000  40.000000  3549.000000
max    9.000000  58.000000  6548.000000

In [70]:
df1 = pd.read_excel(file)
df1

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [71]:
 df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   0           9 non-null      int64
 1   First Name  9 non-null      object
 2   Last Name   9 non-null      object
 3   Gender      9 non-null      object
 4   Country     9 non-null      object
 5   Age         9 non-null      int64
 6   Date        9 non-null      object
 7   Id          9 non-null      int64
dtypes: int64(3), object(5)
memory usage: 708.0+ bytes

In [72]:
df1.describe()

              0        Age           Id
count  9.000000   9.000000     9.000000
mean   5.000000  35.888889  2989.333333
std    2.738613  13.147666  1511.344517
min    1.000000  24.000000  1562.000000
25%    3.000000  25.000000  2456.000000
50%    5.000000  32.000000  2554.000000
75%    7.000000  40.000000  3549.000000
max    9.000000  58.000000  6548.000000

In [74]:
df1.isna() # It gives true on the data position if there is no data is present or there is null
           # Returns false when there is data present

       0  First Name  Last Name  Gender  Country    Age   Date     Id
0  False       False      False   False    False  False  False  False
1  False       False      False   False    False  False  False  False
2  False       False      False   False    False  False  False  False
3  False       False      False   False    False  False  False  False
4  False       False      False   False    False  False  False  False
5  False       False      False   False    False  False  False  False
6  False       False      False   False    False  False  False  False
7  False       False      False   False    False  False  False  False
8  False       False      False   False    False  False  False  False

In [75]:
df1.isna().sum() # It returns the sum of null value count of each column

0             0
First Name    0
Last Name     0
Gender        0
Country       0
Age           0
Date          0
Id            0
dtype: int64

# How to access DataFrame data

In [76]:
user_df

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [84]:
x = user_df['First Name']
type(x)  # type is Series

pandas.core.series.Series

In [99]:
x = user_df[['First Name','Last Name']]# When we access multiple columns then use double bracket( [[ ]] ).

print(x)
print("\n")
print(type(x)) # type is DataFrame
print("\n")
print(user_df['First Name'])                                   # When we access single column then we can use single bracket( [ ] ).

  First Name  Last Name
0      Dulce      Abril
1       Mara  Hashimoto
2     Philip       Gent
3   Kathleen     Hanner
4    Nereida    Magwood
5     Gaston      Brumm
6       Etta       Hurn
7    Earlean     Melgar
8   Vincenza    Weiland


<class 'pandas.core.frame.DataFrame'>


0       Dulce
1        Mara
2      Philip
3    Kathleen
4     Nereida
5      Gaston
6        Etta
7     Earlean
8    Vincenza
Name: First Name, dtype: object

In [97]:
user_df[['First Name', 'Last Name']]

  First Name  Last Name
0      Dulce      Abril
1       Mara  Hashimoto
2     Philip       Gent
3   Kathleen     Hanner
4    Nereida    Magwood
5     Gaston      Brumm
6       Etta       Hurn
7    Earlean     Melgar
8   Vincenza    Weiland

### .head()

In [100]:
 user_df.head() # It returns the first 5 rows

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468

In [104]:
 user_df.head(7) # We can pass the number of rows we want to access

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598

### .tail()

In [ ]:
# It returns the last 5 rows 
# We can pass the number of rows we want to accesss as a parameter to it

In [106]:
user_df.tail() # Last 5

   0 First Name Last Name  Gender        Country  Age        Date    Id
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston     Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean    Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza   Weiland  Female  United States   40  21/05/2015  6548

In [107]:
user_df.tail(3) # Last 3

   0 First Name Last Name  Gender        Country  Age        Date    Id
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean    Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza   Weiland  Female  United States   40  21/05/2015  6548

In [116]:
user_df.tail(10)  # Last 10

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

## Slicing

In [112]:
df = pd.DataFrame(np.random.randint(10, 50,size = (12,5)))
df

     0   1   2   3   4
0   16  40  45  47  41
1   37  39  36  28  39
2   14  29  24  33  11
3   32  13  11  23  38
4   12  28  18  26  42
5   32  26  35  39  41
6   42  27  42  44  17
7   34  12  33  28  18
8   37  31  36  13  46
9   12  30  29  13  30
10  36  18  39  44  37
11  30  15  46  22  14

In [114]:
df[:5] # It will also print the first 5 rows similar to the df.head()

    0   1   2   3   4
0  16  40  45  47  41
1  37  39  36  28  39
2  14  29  24  33  11
3  32  13  11  23  38
4  12  28  18  26  42

In [128]:
df[:7] # this is slicing

    0   1   2   3   4
0  16  40  45  47  41
1  37  39  36  28  39
2  14  29  24  33  11
3  32  13  11  23  38
4  12  28  18  26  42
5  32  26  35  39  41
6  42  27  42  44  17

In [119]:
df[[1,2,4]] # We can access the multiple columns by passing the column names inside list , Here the column names are numbers so we passed them without the double or single quote

     1   2   4
0   40  45  41
1   39  36  39
2   29  24  11
3   13  11  38
4   28  18  42
5   26  35  41
6   27  42  17
7   12  33  18
8   31  36  46
9   30  29  30
10  18  39  37
11  15  46  14

In [126]:
# We can access the head i.e first 5 data elemennt of particular columns ->>

df[[0,1,4]].head()

    0   1   4
0  16  40  41
1  37  39  39
2  14  29  11
3  32  13  38
4  12  28  42

In [129]:
# We can also perform slicing on above 

df[[1,2,4]][:5] # i.e we can access particular number of rows with particular columns

    1   2   4
0  40  45  41
1  39  36  39
2  29  24  11
3  13  11  38
4  28  18  42

In [133]:
# Accessing a single row

df[7:8]

    0   1   2   3   4
7  34  12  33  28  18

In [136]:
# Slicing is used to access the particular element 

user_df[['First Name', 'Age', 'Gender']][3:7]

  First Name  Age  Gender
3   Kathleen   25  Female
4    Nereida   58  Female
5     Gaston   24    Male
6       Etta   56  Female

## Another way to access data

### .loc()

In [243]:
# Syntax ->> df.loc[[row lables] , [column lables]] === df.loc[[row_start_lable : row_stop_lable: step], [col_start_lable: col_stop_lable : step]]

In [200]:
# It returns the actual value of index/label
# Syntax ->> df.loc[row_label, column_label]

# It pass it the location not the indexes i.e see below line in which we have passed the location 0 to 8 and it will print the data from 0 to 8 th location 
# If this was indexes then data will printed from 0 index to 7 index i.e less one than last index

# Lets see the Difference

x = df.loc[0:8] # location is passed
print(x)  # printed from index 0 to 8

print("\n")

y = df[0:8]
print(y) # printed from index 0 to 7

    a   b   c   d   e
0  16  40  45  47  41
1  37  39  36  28  39
2  14  29  24  33  11
3  32  13  11  23  38
4  12  28  18  26  42
5  32  26  35  39  41
6  42  27  42  44  17
7  34  12  33  28  18
8  37  31  36  13  46


    a   b   c   d   e
0  16  40  45  47  41
1  37  39  36  28  39
2  14  29  24  33  11
3  32  13  11  23  38
4  12  28  18  26  42
5  32  26  35  39  41
6  42  27  42  44  17
7  34  12  33  28  18

In [201]:
df.columns = ['a','b','c','d','e']

In [242]:
df1.loc[1:7]

   0 First Name  Last Name  Gender        Country  Age        Date    Id
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456

In [173]:
df1

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [178]:
# We can access number of rows we want and particular column as below

df1.loc[0:5, 'First Name']

0       Dulce
1        Mara
2      Philip
3    Kathleen
4     Nereida
5      Gaston
Name: First Name, dtype: object

In [193]:
# With multiple columns

location = df1.loc[0:5, ['First Name', 'Last Name']]  # In locaion we pass lables like, df.loc[startlable:endlable, [list of columns]]
print("By location : \n",location,"\n")

# using Slicing
slicing = df1[['First Name', 'Last Name']][0:6]  # In slicing we pass indexes
print("Slicing : \n",slicing)

By location :
   First Name  Last Name
0      Dulce      Abril
1       Mara  Hashimoto
2     Philip       Gent
3   Kathleen     Hanner
4    Nereida    Magwood
5     Gaston      Brumm

Slicing :
   First Name  Last Name
0      Dulce      Abril
1       Mara  Hashimoto
2     Philip       Gent
3   Kathleen     Hanner
4    Nereida    Magwood
5     Gaston      Brumm

In [199]:
# We can also pass the list of locations/lables which we want

df1.loc[[0,3,7], ['First Name', 'Last Name','Age']]

  First Name Last Name  Age
0      Dulce     Abril   32
3   Kathleen    Hanner   25
7    Earlean    Melgar   27

### .iloc()

In [234]:
# Stands for index location
# df.iloc[row_index, column_index] === df.iloc[start_index : stop_index : step , start_index : stop_index : step]

In [204]:
df1

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [207]:
df1.iloc[2] # it only returns the 2nd row with its column names/lables

0                      3
First Name        Philip
Last Name           Gent
Gender              Male
Country           France
Age                   36
Date          21/05/2015
Id                  2587
Name: 2, dtype: object

In [209]:
# To access the particular data from dataFrame use row_index and column_index

df1.iloc[1,2] # Data from 1st row and 2nd column is printed

'Hashimoto'

In [210]:
# We can also access the overall Dataframe  as Below ->>

df1.iloc[:,:]

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [214]:
df1.iloc[:2] # It returns the only 2 rows i.e rows of index 0 and 1

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582

In [220]:
df1.iloc[4:7] # slicing using iloc()

   0 First Name Last Name  Gender        Country  Age        Date    Id
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston     Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598

In [223]:
df1.iloc[4:7, 2:6] # slicing 4:7 is for rows and slicing 2:6 is for columns

  Last Name  Gender        Country  Age
4   Magwood  Female  United States   58
5     Brumm    Male  United States   24
6      Hurn  Female  Great Britain   56

In [227]:
df1.iloc[2:5, 0:8] # for slicing we have used the indexes not the location

   0 First Name Last Name  Gender        Country  Age        Date    Id
2  3     Philip      Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen    Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468

In [230]:
df1.iloc[4:7, ::2] # if we used double colon then valu after the second colon act as a step means the columns having gap between them is step value are only printed

   0 Last Name        Country        Date
4  5   Magwood  United States  16/08/2016
5  6     Brumm  United States  21/05/2015
6  7      Hurn  Great Britain  15/10/2017

In [233]:
# we can also use this for rows

df1.iloc[::3, 0:8] # rows  after the distance 3 are only printed

   0 First Name Last Name  Gender        Country  Age        Date    Id
0  1      Dulce     Abril  Female  United States   32  15/10/2017  1562
3  4   Kathleen    Hanner  Female  United States   25  15/10/2017  3549
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598

In [235]:
df1.iloc[2:8:2, 0:8:3]

   0  Gender        Date
2  3    Male  21/05/2015
4  5  Female  16/08/2016
6  7  Female  15/10/2017

In [236]:
df1.iloc[2:8:2, 0:8]

   0 First Name Last Name  Gender        Country  Age        Date    Id
2  3     Philip      Gent    Male         France   36  21/05/2015  2587
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598

In [237]:
df1

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [240]:
# We cann also access the particular rows and columns by passing the lists of rows and indexes 

df1.iloc[[1,2,3,4, 6,8],[1,3,5]]

  First Name  Gender  Age
1       Mara  Female   25
2     Philip    Male   36
3   Kathleen  Female   25
4    Nereida  Female   58
6       Etta  Female   56
8   Vincenza  Female   40

In [253]:
# Difference between the df.iloc() and df.loc() ->> 
# 1. df.loc() ->> in loc() we can pass the lables i.e column names not the indices
# 2. df.iloc() ->> in iloc() we can pass the indices not the lables 

# see with example

print(df1)

print("\n")
loc = df1.loc[[1,3,4,6,8], ['First Name' ,'Last Name', 'Age']]
print("By using Location : \n\n",loc)

print("\n")
index_loc = df1.iloc[[1,3,4,6],[1,4,6]]
print("By  Using Index Location : \n\n",index_loc)

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548


By using Location :

   First Name  Last Name  Age
1       Mara  Hashimoto   25
3   Kathleen     Hanner   25
4    Nereida    Magwood   58
6       Etta       Hurn   56
8   Vincenza    Weiland   40


By  Using Index Location :

   First Name        Country        Date
1       Mara  Great Britain  16/08/2016
3   Kathleen  United States  15/10/2017
4    Nereida  United States  16/08/2016
6       Etta  Great Britain  15/10/2017

In [259]:
# We can perform the slicing after accessing the particular columns on that columns 

df1[['First Name' ,'Gender', 'Age']].iloc[2:8:2, 0:2]  # while slicing we used the column indices that can be applied only on the accessed columns i.e 0:2 ->> can access only the 0th and 1st index column from ['First Name' ,'Gender', 'Age']

  First Name  Gender
2     Philip    Male
4    Nereida  Female
6       Etta  Female

### Negative Indexing

In [271]:
# We can also prform Negative Indexing 

df1

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [274]:

df1[-5:]

   0 First Name Last Name  Gender        Country  Age        Date    Id
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston     Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta      Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean    Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza   Weiland  Female  United States   40  21/05/2015  6548

In [283]:
df1.iloc[-6:-3]

   0 First Name Last Name  Gender        Country  Age        Date    Id
3  4   Kathleen    Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida   Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston     Brumm    Male  United States   24  21/05/2015  2554

# Create CSV and EXCEL File

In [287]:
df2 = df1
df2

   0 First Name  Last Name  Gender        Country  Age        Date    Id
0  1      Dulce      Abril  Female  United States   32  15/10/2017  1562
1  2       Mara  Hashimoto  Female  Great Britain   25  16/08/2016  1582
2  3     Philip       Gent    Male         France   36  21/05/2015  2587
3  4   Kathleen     Hanner  Female  United States   25  15/10/2017  3549
4  5    Nereida    Magwood  Female  United States   58  16/08/2016  2468
5  6     Gaston      Brumm    Male  United States   24  21/05/2015  2554
6  7       Etta       Hurn  Female  Great Britain   56  15/10/2017  3598
7  8    Earlean     Melgar  Female  United States   27  16/08/2016  2456
8  9   Vincenza    Weiland  Female  United States   40  21/05/2015  6548

In [298]:
df2.to_csv('test2.csv',index=False)  #index=False will does not return the indices inside the .csv file

In [295]:
df2.to_excel('test1.xlsx',index = False)