# Pandas Basics

In [1]:
import pandas as pd
import numpy as np

## Two Data Structures

In [2]:
# 1. DataFrame :
#     2D Data >> Multiple columns
#     It consists of multiple 1D Data

# 2. Series :
#     1D >> Single column

# Use : 
#     1. Used for working with Datasets

### Forms of Data to Deal with

In [4]:
# 1. CSV
# 2. Excel
# 3. JSON
# 4. Database(MongoDB, SQLite, Oracle)

In [7]:
arr = np.random.randint(20,40, size = (10, 5))
df = pd.DataFrame(arr)
df

    0   1   2   3   4
0  35  35  20  22  35
1  34  32  31  20  31
2  25  32  38  22  35
3  29  36  39  20  29
4  21  21  26  29  37
5  38  20  38  30  39
6  32  27  22  22  22
7  22  23  34  23  27
8  26  20  34  22  24
9  35  26  26  39  39

In [10]:
# We can give column names for particular column

arr = np.random.randint(20,40, size = (10, 5))
df = pd.DataFrame(arr, columns= ['a', 'b','c','d','e'])
df

    a   b   c   d   e
0  24  31  39  30  29
1  38  20  34  30  36
2  30  22  24  31  30
3  31  25  32  31  32
4  22  38  32  25  26
5  23  27  21  39  32
6  30  24  35  23  25
7  38  37  33  20  32
8  37  22  35  20  24
9  32  24  21  29  37

In [15]:
# Another Method to give the column names 

arr = np.random.randint(20,40, size = (10, 5))
df = pd.DataFrame(arr, columns= list('abcde')) # list() method separate the each character from string given as parametre and makes the list of this characters. 
df

    a   b   c   d   e
0  21  24  28  28  20
1  33  26  39  20  22
2  24  34  30  31  25
3  24  25  39  32  22
4  21  29  39  36  38
5  21  32  29  39  31
6  35  26  37  29  30
7  26  37  29  32  32
8  36  34  27  38  26
9  31  29  22  21  34

In [16]:
type(df)

pandas.core.frame.DataFrame

In [18]:
# Printing any series(column)

s1 = df['b'] # series b (column b) will be printed
s1

0    24
1    26
2    34
3    25
4    29
5    32
6    26
7    37
8    34
9    29
Name: b, dtype: int32

In [19]:
type(s1)

pandas.core.series.Series

In [25]:
num = [1,2,3,4,5]
num2 = [11,12,13,14,15]
num3 = [19,12,24,32,22]
df = pd.DataFrame([num,num2,num3]) # We have to pass the multiple lists inside [] i.e list
df

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15
2  19  12  24  32  22

In [26]:
# We can Transpose the DataFrame i.e Rows converted into Columns

df.T

   0   1   2
0  1  11  19
1  2  12  12
2  3  13  24
3  4  14  32
4  5  15  22

In [29]:
# Making an Empty DataFrame
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [40]:
df = pd.DataFrame()
df['A'] = [1,2,3,4,5,6,7,8,9,10]
df['B'] = [11,12,13,14,15,16,17,18,19,20]           # We can Pass List
df['C'] = np.array((12,21,43,54,21,54,76,98,88,45)) # We can Pass Array
df['D'] = (12,23,34,66,76,98,31,35,67,90)           # We can Pass tuple

# df['E'] = {1,3,4,5,6,7,8,9,10,53}     # We can Not Pass set to DataFrame

df

    A   B   C   D
0   1  11  12  12
1   2  12  21  23
2   3  13  43  34
3   4  14  54  66
4   5  15  21  76
5   6  16  54  98
6   7  17  76  31
7   8  18  98  35
8   9  19  88  67
9  10  20  45  90

In [42]:
# We can Create Data Frame using Dictionary

data = {'Col_A' : np.arange(1,6),
        'Col_B' : [5,6,7,8,9]
       }
df = pd.DataFrame(data)
df

   Col_A  Col_B
0      1      5
1      2      6
2      3      7
3      4      8
4      5      9