# Pandas Export

- to_csv
- to_excel
- to_html
- to_json
- to_sql

In [2]:
import pandas as pd

## 1. to_csv

In [11]:
df = pd.read_csv('deliveries.csv')
df

,delivery_id,delivery_order_id,driver_id,delivery_distance_meters,delivery_status
0,2174658,68413340,8378.0,5199.0,DELIVERED
1,2174660,68414309,2473.0,410.0,DELIVERED
2,2174661,68416230,7615.0,3784.0,DELIVERED
3,2174663,68412721,8378.0,5714.0,DELIVERED
4,2174675,68414018,10463.0,3746.0,DELIVERED
...,...,...,...,...,...
378838,3134825,87083078,7615.0,8110.0,DELIVERED
378839,3135417,87660079,26223.0,14454.0,DELIVERED
378840,3135849,82340127,55429.0,2546.0,DELIVERED
378841,3142829,88586792,47016.0,3106.0,DELIVERED
378842,3144739,93026454,10504.0,2919.0,DELIVERED

In [16]:
temp_df = df.groupby('driver_id')['delivery_distance_meters'].sum().reset_index()

# here sum of delivey_distannce in meters of each driver is printed

temp_df

      driver_id  delivery_distance_meters
0         133.0                   45188.0
1         138.0                  323114.0
2         140.0                 1462661.0
3         143.0                    3773.0
4         148.0                 1253116.0
...         ...                       ...
4578    66243.0                    8315.0
4579    66260.0                    3107.0
4580    66271.0                    2639.0
4581    66457.0                   22881.0
4582    66459.0                    6127.0

[4583 rows x 2 columns]

In [20]:
temp_df.to_csv('drivers_total_distance.csv',index = False)  # In the current folder csv file will be created.

In [18]:
temp_df

      driver_id  delivery_distance_meters
0         133.0                   45188.0
1         138.0                  323114.0
2         140.0                 1462661.0
3         143.0                    3773.0
4         148.0                 1253116.0
...         ...                       ...
4578    66243.0                    8315.0
4579    66260.0                    3107.0
4580    66271.0                    2639.0
4581    66457.0                   22881.0
4582    66459.0                    6127.0

[4583 rows x 2 columns]

## 2. to_excel()

In [21]:
temp_df.to_excel('drivers_total_distance.xlsx')  # excel file will created in current folder

### giving Excel sheet name

In [22]:
temp_df.to_excel('output.xlsx',sheet_name='drivers')

### Adding multiple sheets

In [23]:
with pd.ExcelWriter('multisheet.xlsx') as writer:
    dataframe_1.to_excel(writer, sheet_name='Sheet_name_1')
    dataframe_2.to_excel(writer, sheet_name='Sheet_name_2')
    dataframe_3.to_excel(writer, sheet_name='Sheet_name_3')

IndexError: At least one sheet must be visible

## 3. to_json()