- the value we impute is called as arbitrary value.
- In this we have to impute the value which is not present in the feature.
- Finding  the arbitrary value (which value is not present in dataset or feature) is difficult.

- Common Arbitrary values-->  -1, 999, 9999, 0, etc.

- There are 2 methods for arbitrary value imputation -> 

        - fillna(arbitrary value)

        - SimpleImputer()

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
data = {
'Age':[22, 58, np.nan, 42, np.nan, 71, 37, 94, 
       np.nan,  6, 12, 33, 74, 64, 70,  9, 34,
       21, 54, 41, 25, 56, np.nan, 12, 12, 62, 25, 13, 32, 58, 86, 38, 51, 95,
       35, 10, 99, 90,  2, 98, 46, 23, 30, 83,  3,  4, 16, 81, 24, np.nan],
'Value':[72, 14, 36, 44, 15, 55, 83, 61, 76, 96, 54, 77, 12, 92, 81, 82, 26,
       43, 75, 50, 99, 10, 98, 50, 71, 44, 27, 73, 36,  8, 64, 84, 49,  1,
       74, 25, 16, 74, 67, 40, 62, 91, 43, 46, 67, 41, 30, 77, 57, 18]
}

In [10]:
df = pd.DataFrame(data)

In [12]:
df['Age'].unique()

array([22., 58., nan, 42., 71., 37., 94.,  6., 12., 33., 74., 64., 70.,
        9., 34., 21., 54., 41., 25., 56., 62., 13., 32., 86., 38., 51.,
       95., 35., 10., 99., 90.,  2., 98., 46., 23., 30., 83.,  3.,  4.,
       16., 81., 24.])

- Finding arbitrary values -->  2 ways

    - checking particular  alue is present in feature or not

    - Finding the minimum and maximum from feature. eg.,  min is 20 and max is 80.  Therefore we can impute another values than this values.

In [ ]:
# Checking particular value are present or not

x = 99 in df['Age'].values
x  # True -> Means 99 is present in dataset

True

In [22]:
x1 = 1 in df['Age'].values
x1  # 1 is not present in dataset

False

In [24]:
# Finding the minimum and maximumm

x2 = df['Age'].min()
x3 = df['Age'].max()

print(x2)
print(x3)

2.0
99.0

In [25]:
# So we can impute the values like 1 and 0.

## 1] Using fillna()

In [71]:
df['Age'] = df['Age'].fillna(1)

In [72]:
df

     Age  Value
0   22.0     72
1   58.0     14
2    1.0     36
3   42.0     44
4    1.0     15
5   71.0     55
6   37.0     83
7   94.0     61
8    1.0     76
9    6.0     96
10  12.0     54
11  33.0     77
12  74.0     12
13  64.0     92
14  70.0     81
15   9.0     82
16  34.0     26
17  21.0     43
18  54.0     75
19  41.0     50
20  25.0     99
21  56.0     10
22   1.0     98
23  12.0     50
24  12.0     71
25  62.0     44
26  25.0     27
27  13.0     73
28  32.0     36
29  58.0      8
30  86.0     64
31  38.0     84
32  51.0     49
33  95.0      1
34  35.0     74
35  10.0     25
36  99.0     16
37  90.0     74
38   2.0     67
39  98.0     40
40  46.0     62
41  23.0     91
42  30.0     43
43  83.0     46
44   3.0     67
45   4.0     41
46  16.0     30
47  81.0     77
48  24.0     57
49   1.0     18

In [80]:
# Imputing with  100

df_x = pd.DataFrame(data)
df_x['Age'] = df_x['Age'].fillna(100)

In [81]:
df_x

      Age  Value
0    22.0     72
1    58.0     14
2   100.0     36
3    42.0     44
4   100.0     15
5    71.0     55
6    37.0     83
7    94.0     61
8   100.0     76
9     6.0     96
10   12.0     54
11   33.0     77
12   74.0     12
13   64.0     92
14   70.0     81
15    9.0     82
16   34.0     26
17   21.0     43
18   54.0     75
19   41.0     50
20   25.0     99
21   56.0     10
22  100.0     98
23   12.0     50
24   12.0     71
25   62.0     44
26   25.0     27
27   13.0     73
28   32.0     36
29   58.0      8
30   86.0     64
31   38.0     84
32   51.0     49
33   95.0      1
34   35.0     74
35   10.0     25
36   99.0     16
37   90.0     74
38    2.0     67
39   98.0     40
40   46.0     62
41   23.0     91
42   30.0     43
43   83.0     46
44    3.0     67
45    4.0     41
46   16.0     30
47   81.0     77
48   24.0     57
49  100.0     18

## Using SimpleImputer()

In [55]:
data_1 = {
'Age':[22, 58, np.nan, 42, np.nan, 71, 37, 94, 
       np.nan,  6, 12, 33, 74, 64, 70,  9, 34,
       21, 54, 41, 25, 56, np.nan, 12, 12, 62, 25, 13, 32, 58, 86, 38, 51, 95,
       35, 10, 99, 90,  2, 98, 46, 23, 30, 83,  3,  4, 16, 81, 24, np.nan],
'Value':[72, 14, 36, 44, 15, 55, 83, 61, 76, 96, 54, 77, 12, 92, 81, 82, 26,
       43, 75, 50, 99, 10, 98, 50, 71, 44, 27, 73, 36,  8, 64, 84, 49,  1,
       74, 25, 16, 74, 67, 40, 62, 91, 43, 46, 67, 41, 30, 77, 57, 18]
}

In [56]:
df_1 = pd.DataFrame(data_1)

In [57]:
df_1

     Age  Value
0   22.0     72
1   58.0     14
2    NaN     36
3   42.0     44
4    NaN     15
5   71.0     55
6   37.0     83
7   94.0     61
8    NaN     76
9    6.0     96
10  12.0     54
11  33.0     77
12  74.0     12
13  64.0     92
14  70.0     81
15   9.0     82
16  34.0     26
17  21.0     43
18  54.0     75
19  41.0     50
20  25.0     99
21  56.0     10
22   NaN     98
23  12.0     50
24  12.0     71
25  62.0     44
26  25.0     27
27  13.0     73
28  32.0     36
29  58.0      8
30  86.0     64
31  38.0     84
32  51.0     49
33  95.0      1
34  35.0     74
35  10.0     25
36  99.0     16
37  90.0     74
38   2.0     67
39  98.0     40
40  46.0     62
41  23.0     91
42  30.0     43
43  83.0     46
44   3.0     67
45   4.0     41
46  16.0     30
47  81.0     77
48  24.0     57
49   NaN     18

In [58]:
from sklearn. model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [63]:
X = df_1.drop(columns=['Value'])
y = df_1['Value']

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [65]:
X_train

     Age
12  74.0
4    NaN
37  90.0
8    NaN
3   42.0
6   37.0
41  23.0
46  16.0
47  81.0
15   9.0
9    6.0
16  34.0
24  12.0
34  35.0
31  38.0
0   22.0
44   3.0
27  13.0
33  95.0
5   71.0
29  58.0
11  33.0
36  99.0
1   58.0
21  56.0
2    NaN
43  83.0
35  10.0
23  12.0
40  46.0
10  12.0
22   NaN
18  54.0
49   NaN
20  25.0
7   94.0
42  30.0
14  70.0
28  32.0
38   2.0

In [66]:
arbitrary_imputer = SimpleImputer(strategy='constant', fill_value=1)

In [67]:
X_train = arbitrary_imputer.fit_transform(X_train)
X_test = arbitrary_imputer.fit_transform(X_test)

In [ ]:
X_train

array([[74.],
       [ 1.],
       [90.],
       [ 1.],
       [42.],
       [37.],
       [23.],
       [16.],
       [81.],
       [ 9.],
       [ 6.],
       [34.],
       [12.],
       [35.],
       [38.],
       [22.],
       [ 3.],
       [13.],
       [95.],
       [71.],
       [58.],
       [33.],
       [99.],
       [58.],
       [56.],
       [ 1.],
       [83.],
       [10.],
       [12.],
       [46.],
       [12.],
       [ 1.],
       [54.],
       [ 1.],
       [25.],
       [94.],
       [30.],
       [70.],
       [32.],
       [ 2.]])

In [70]:
X_test

array([[64.],
       [98.],
       [86.],
       [ 4.],
       [21.],
       [24.],
       [25.],
       [62.],
       [51.],
       [41.]])