In [68]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [69]:
age = np.random.randint(20,80,200)
fare = np.random.randint(1,100,200)
survived = np.random.randint(0, 2,200)

In [70]:
age

array([66, 60, 56, 23, 77, 24, 60, 63, 74, 74, 28, 67, 25, 38, 55, 65, 76,
       46, 30, 52, 77, 48, 24, 32, 54, 75, 78, 53, 32, 63, 24, 38, 56, 52,
       65, 62, 24, 39, 23, 50, 54, 32, 56, 77, 66, 48, 77, 49, 57, 22, 34,
       40, 65, 43, 69, 35, 33, 62, 35, 35, 63, 70, 62, 48, 68, 54, 59, 58,
       38, 20, 22, 39, 33, 65, 40, 31, 50, 53, 77, 52, 36, 41, 28, 56, 52,
       31, 53, 75, 55, 57, 37, 51, 78, 27, 22, 42, 39, 43, 67, 43, 60, 68,
       30, 21, 23, 31, 28, 32, 49, 57, 22, 30, 51, 37, 67, 54, 26, 21, 23,
       23, 63, 53, 24, 58, 77, 79, 25, 79, 37, 36, 42, 78, 74, 68, 63, 30,
       55, 55, 51, 73, 53, 40, 36, 73, 73, 79, 46, 45, 64, 46, 60, 22, 28,
       78, 56, 76, 70, 56, 60, 21, 56, 27, 34, 46, 72, 39, 25, 39, 24, 70,
       44, 48, 56, 74, 68, 79, 65, 69, 50, 22, 34, 37, 23, 78, 65, 30, 57,
       49, 64, 68, 75, 46, 22, 32, 41, 70, 39, 27, 77, 22], dtype=int32)

In [71]:
fare

array([76, 53, 80, 19, 63, 61, 98, 44, 90, 15, 81, 59, 69, 86, 36, 83, 99,
       72, 95, 78, 57,  4, 39, 53, 82, 67, 64, 17, 44, 36, 22,  3, 80, 15,
       68,  5, 13, 53, 62, 97, 94, 64, 47, 55, 40, 46, 34,  1, 26, 73, 22,
       41, 71, 11, 12, 42, 44, 78, 69, 95, 31, 56, 91, 52, 75, 92, 37, 91,
        6, 12, 50, 20, 87,  2, 94, 75, 77, 83,  4, 25, 16, 19, 60, 47, 73,
       88, 13, 43, 44, 81, 25, 75, 48,  5, 61, 35, 24, 86, 36, 83, 70, 68,
       96, 53, 84, 62, 61, 69, 82, 79, 71, 51, 85, 69, 66, 53, 22, 42, 88,
       49, 19, 58, 71, 78, 18,  4, 95,  5, 46, 96, 53, 67, 12, 31, 21, 16,
       15, 91, 50,  4, 23, 94, 79, 72, 16, 31, 34, 39, 56, 10, 65,  1, 52,
       94, 66,  4, 59, 69, 66, 90, 84, 24, 11, 67, 86, 41, 10, 53,  4, 38,
       18, 35, 58, 41, 75, 93, 21, 32, 16, 40, 16, 12, 58, 60, 19, 39, 76,
       55, 42, 79,  8, 57, 87, 82, 61, 74, 82, 15, 24, 92], dtype=int32)

In [72]:
survived

array([1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0], dtype=int32)

In [73]:
data = {
    'Age':[43, np.nan, 46, 39, 73, 77, 27, 74, 73, 40, 63, 48, 63, np.nan, 41, 51, 53,
       34, 64, 61, 21, np.nan, 34, 48, 63, 54, 47, np.nan, 22, 56, 49, 36, 43, 75,
       38, 31, 31, 32, 50, 63, np.nan, 76, 31, 31, 63, 59, 64, np.nan, 42, 78, 20,
       np.nan, 41, 30, 42, 42, 69, 36, 53, 72, np.nan, 35, 37, 38, 75, 54, 78, 72,
       70, 61, 24, 60, np.nan, 57, 79, 75, 64, 66, 54, 63, 47, np.nan, 24, 70, 24,
       76, 66, np.nan, 44, 37, 69, 20, 40, 44, 55, 45, 30, 34, 60, 50, 65, 41,
       32, 37, 48, 68, 52, 33, 22, 69, 68, 56, 31, 57, 40, 44, 64, 51, 48,
       66, 79, np.nan, 63, 55, np.nan, 45, 45, np.nan, 43, 21, 76, 26, 55, np.nan, 35, 51,
       np.nan, 53, 48, np.nan, 37, 52, 34, np.nan, 29, 30, 53, 27, 30, 68, 68, 46, 22,
       77, 36, 75, 56, 61, 66, 27, 33, 36, 72, 30, np.nan, 58, 30, 20, 23, np.nan,
       66, 59, 57, 69, 73, 46, 62, 69, 22, np.nan, 28, 41, 40, 30, 51, 49, 53,
       34, np.nan, 45, 34, 23, 36, np.nan, 29, 62, np.nan, 52, 53, 73],
    'Fare':[89, 88, 28, 11,  3, 95, 38, 78, 20, 52, 16, 99, 69, 94, 26, 96, 75,
       66,  8,  5, 48, 67, 32, 54, 30,  1, 66, 68, 67, 12, 38,  8, 23, 82,
       88, 28, 18, 91, 62, 27, 41, 29, 80, 28, 65, 97, 36, 63, 56, 12, 43,
       21, 14, 26, 43, 71,  8, 33, 42, 81, 32, 13, 35, 54, 69, 25,  3, 92,
       61, 21, 90, 32, 32, 28, 13, 61,  5, 29, 56, 75, 29, 94,  5, 55,  4,
       37,  6, 87, 74, 96, 12, 43,  3, 15, 89, 25, 47, 56, 26, 71, 60, 67,
       46, 65, 81, 97, 11, 23,  3,  1, 94, 10, 30, 54, 77, 54, 24, 60,  3,
       39, 24, 85, 28, 96, 10, 99, 30, 25, 66, 64, 63, 19, 10, 37, 21, 29,
       26, 80, 47, 38, 25, 79, 34, 94, 40,  5, 35, 11, 53, 76, 38, 39, 43,
       78, 11, 57, 92, 59, 66, 51, 47, 92, 32, 25, 91, 63, 63, 42,  2, 55,
       56, 12, 28, 13, 78, 14, 20,  5, 37, 25, 85, 20, 58, 72, 72, 87, 25,
       79, 52, 55, 62, 15, 67,  9, 38, 64,  1, 81, 75, 23],
    'Survived':[0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0]
}

In [74]:
df = pd.DataFrame(data)

In [75]:
df.head()

    Age  Fare  Survived
0  43.0    89         0
1   NaN    88         0
2  46.0    28         1
3  39.0    11         0
4  73.0     3         0

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

In [77]:
si = SimpleImputer(strategy = 'mean')
df[['Age']] = si.fit_transform(df[['Age']])

In [78]:
df.head()

         Age  Fare  Survived
0  43.000000    89         0
1  49.136364    88         0
2  46.000000    28         1
3  39.000000    11         0
4  73.000000     3         0

In [79]:
X = df.drop(columns = ['Survived'])
y = df['Survived']

In [80]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 42)

In [81]:
X_train

           Age  Fare
79   63.000000    75
197  52.000000    81
38   50.000000    62
24   63.000000    30
122  63.000000    28
..         ...   ...
106  52.000000    11
14   41.000000    26
92   40.000000     3
179  49.136364    25
102  32.000000    46

[160 rows x 2 columns]

In [82]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [83]:
y_pred = clf.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.425

In [85]:
# Missing Indicator Using Simple Indicator

In [86]:
si = SimpleImputer(add_indicator = True)

In [87]:
X_train = si.fit_transform(X_train)
X_test = si.fit_transform(X_test)

In [93]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)

In [96]:
X_train

             0     1
0    63.000000  75.0
1    52.000000  81.0
2    50.000000  62.0
3    63.000000  30.0
4    63.000000  28.0
..         ...   ...
155  52.000000  11.0
156  41.000000  26.0
157  40.000000   3.0
158  49.136364  25.0
159  32.000000  46.0

[160 rows x 2 columns]

In [94]:
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression()
clf1.fit(X_train, y_train)
y_pred1 = clf1.predict(X_test)

In [95]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.425